version: '3'

services:

  client:
    container_name: client
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true